export async function mockData(params) {
    return({
            "data": [
                {
                    "id": 140,
                    "name": "Kaichou wa Maid-sama!",
                    "eng_name": "Class President is a Maid!",
                    "rus_name": "Президент студсовета — горничная!",
                    "cover": "hg18y1xD1uRx",
                    "slug": "kaichou_wa_maid-sama",
                    "type_id": 1,
                    "created_at": "2016-05-26T08:51:49.000000Z",
                    "updated_at": "2023-12-23T18:14:41.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kaichou_wa_maid-sama/cover/hg18y1xD1uRx_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kaichou_wa_maid-sama/cover/hg18y1xD1uRx_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kaichou_wa_maid-sama/cover/hg18y1xD1uRx_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kaichou_wa_maid-sama/cover/hg18y1xD1uRx_thumb.jpg",
                    "href": "https://mangalib.me/kaichou_wa_maid-sama",
                    "title_status_id": null
                },
                {
                    "id": 5558,
                    "name": "Tsuiraku JK to Haijin Kyoushi",
                    "eng_name": "Love Me Before You Die",
                    "rus_name": "Проблемная старшеклассница и непутевый учитель",
                    "cover": "d2irKZWrUzOS",
                    "slug": "tsuiraku-jk-to-haijin-kyoushi",
                    "type_id": 1,
                    "created_at": "2018-08-10T05:16:55.000000Z",
                    "updated_at": "2023-12-23T18:14:51.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/tsuiraku-jk-to-haijin-kyoushi/cover/d2irKZWrUzOS_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/tsuiraku-jk-to-haijin-kyoushi/cover/d2irKZWrUzOS_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/tsuiraku-jk-to-haijin-kyoushi/cover/d2irKZWrUzOS_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/tsuiraku-jk-to-haijin-kyoushi/cover/d2irKZWrUzOS_thumb.jpg",
                    "href": "https://mangalib.me/tsuiraku-jk-to-haijin-kyoushi",
                    "title_status_id": null
                },
                {
                    "id": 39062,
                    "name": "Shokei Sareta Kenja wa Lich ni Tensei Shite Shinryaku Sensou wo Hajimaru",
                    "eng_name": "The Executed Sage Is Reincarnated as a Lich and Starts an All-Out War",
                    "rus_name": "Казнённый мудрец перевоплощается в Короля Нежити и начинает новую войну!",
                    "cover": "If3ZKgj27zV8",
                    "slug": "the-executed-sage-is-reincarnated-as-a-lich-and-starts-an-all-out-war",
                    "type_id": 1,
                    "created_at": "2020-07-02T13:04:40.000000Z",
                    "updated_at": "2023-12-23T18:14:53.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/the-executed-sage-is-reincarnated-as-a-lich-and-starts-an-all-out-war/cover/If3ZKgj27zV8_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/the-executed-sage-is-reincarnated-as-a-lich-and-starts-an-all-out-war/cover/If3ZKgj27zV8_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/the-executed-sage-is-reincarnated-as-a-lich-and-starts-an-all-out-war/cover/If3ZKgj27zV8_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/the-executed-sage-is-reincarnated-as-a-lich-and-starts-an-all-out-war/cover/If3ZKgj27zV8_thumb.jpg",
                    "href": "https://mangalib.me/the-executed-sage-is-reincarnated-as-a-lich-and-starts-an-all-out-war",
                    "title_status_id": null
                },
                {
                    "id": 1436,
                    "name": "Monster",
                    "eng_name": "Monster: Horrible Story",
                    "rus_name": "Монстр: Ужасная история",
                    "cover": "k24I08p4QuWb",
                    "slug": "monster",
                    "type_id": 1,
                    "created_at": "2016-08-30T08:58:04.000000Z",
                    "updated_at": "2023-12-23T18:14:16.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/monster/cover/k24I08p4QuWb_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/monster/cover/k24I08p4QuWb_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/monster/cover/k24I08p4QuWb_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/monster/cover/k24I08p4QuWb_thumb.jpg",
                    "href": "https://mangalib.me/monster",
                    "title_status_id": null
                },
                {
                    "id": 18743,
                    "name": "Yuusha Goikkou no Kaerimichi",
                    "eng_name": "Heroes return home",
                    "rus_name": "Возвращение героев домой",
                    "cover": "Bcjd7MU4Pzpk",
                    "slug": "yuusha-goikkou-no-kaerimichi",
                    "type_id": 1,
                    "created_at": "2019-11-22T13:49:46.000000Z",
                    "updated_at": "2023-12-23T18:13:51.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/yuusha-goikkou-no-kaerimichi/cover/Bcjd7MU4Pzpk_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/yuusha-goikkou-no-kaerimichi/cover/Bcjd7MU4Pzpk_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/yuusha-goikkou-no-kaerimichi/cover/Bcjd7MU4Pzpk_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/yuusha-goikkou-no-kaerimichi/cover/Bcjd7MU4Pzpk_thumb.jpg",
                    "href": "https://mangalib.me/yuusha-goikkou-no-kaerimichi",
                    "title_status_id": null
                },
                {
                    "id": 716,
                    "name": "Re:Monster",
                    "eng_name": "Reincarnated: Monster",
                    "rus_name": "Перерождение: Монстр",
                    "cover": "lIDZYqcAm8aH",
                    "slug": "remonster",
                    "type_id": 1,
                    "created_at": "2016-06-05T23:44:38.000000Z",
                    "updated_at": "2023-12-23T18:14:30.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/remonster/cover/lIDZYqcAm8aH_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/remonster/cover/lIDZYqcAm8aH_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/remonster/cover/lIDZYqcAm8aH_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/remonster/cover/lIDZYqcAm8aH_thumb.jpg",
                    "href": "https://mangalib.me/remonster",
                    "title_status_id": null
                },
                {
                    "id": 689,
                    "name": "Nanatsu no Taizai",
                    "eng_name": "The Seven Deadly Sins",
                    "rus_name": "Семь смертных грехов",
                    "cover": "JrS5rhmpwb1F",
                    "slug": "nanatsu-no-taizai",
                    "type_id": 1,
                    "created_at": "2016-06-05T10:19:39.000000Z",
                    "updated_at": "2023-12-23T18:14:36.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/nanatsu-no-taizai/cover/JrS5rhmpwb1F_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/nanatsu-no-taizai/cover/JrS5rhmpwb1F_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/nanatsu-no-taizai/cover/JrS5rhmpwb1F_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/nanatsu-no-taizai/cover/JrS5rhmpwb1F_thumb.jpg",
                    "href": "https://mangalib.me/nanatsu-no-taizai",
                    "title_status_id": null
                },
                {
                    "id": 43762,
                    "name": "Meccha Shoukan Sareta Ken",
                    "eng_name": "Summoned to a parallel fantasy world many times",
                    "rus_name": "Призванный в параллельные фэнтези миры несколько раз",
                    "cover": "rKBfV7kQclR8",
                    "slug": "meccha-shoukan-sareta-ken",
                    "type_id": 1,
                    "created_at": "2020-08-12T21:03:30.000000Z",
                    "updated_at": "2023-12-23T18:14:00.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/meccha-shoukan-sareta-ken/cover/rKBfV7kQclR8_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/meccha-shoukan-sareta-ken/cover/rKBfV7kQclR8_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/meccha-shoukan-sareta-ken/cover/rKBfV7kQclR8_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/meccha-shoukan-sareta-ken/cover/rKBfV7kQclR8_thumb.jpg",
                    "href": "https://mangalib.me/meccha-shoukan-sareta-ken",
                    "title_status_id": null
                },
                {
                    "id": 3819,
                    "name": "Aku no Hana",
                    "eng_name": "The Flowers of Evil (Oshimi Shuzo)",
                    "rus_name": "Цветы зла",
                    "cover": "6P2rfkYF1MIr",
                    "slug": "aku-no-hana",
                    "type_id": 1,
                    "created_at": "2018-02-02T02:03:41.000000Z",
                    "updated_at": "2023-12-23T18:13:38.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/aku-no-hana/cover/6P2rfkYF1MIr_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/aku-no-hana/cover/6P2rfkYF1MIr_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/aku-no-hana/cover/6P2rfkYF1MIr_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/aku-no-hana/cover/6P2rfkYF1MIr_thumb.jpg",
                    "href": "https://mangalib.me/aku-no-hana",
                    "title_status_id": null
                },
                {
                    "id": 59215,
                    "name": "Kimi ni Koisuru Satsujinki",
                    "eng_name": "Killer in Love",
                    "rus_name": "Очарованный ею убийца",
                    "cover": "sZt7KS384HyC",
                    "slug": "kimi-ni-koisuru-satsujinki",
                    "type_id": 1,
                    "created_at": "2021-01-09T13:08:26.000000Z",
                    "updated_at": "2023-12-23T18:15:36.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kimi-ni-koisuru-satsujinki/cover/sZt7KS384HyC_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kimi-ni-koisuru-satsujinki/cover/sZt7KS384HyC_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kimi-ni-koisuru-satsujinki/cover/sZt7KS384HyC_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kimi-ni-koisuru-satsujinki/cover/sZt7KS384HyC_thumb.jpg",
                    "href": "https://mangalib.me/kimi-ni-koisuru-satsujinki",
                    "title_status_id": null
                },
                {
                    "id": 18153,
                    "name": "Noraneko to Ookami",
                    "eng_name": "Stray cat and wolf",
                    "rus_name": "Бездомная кошка и волк",
                    "cover": "kTj1R8S5BsDD",
                    "slug": "noraneko-to-ookami",
                    "type_id": 1,
                    "created_at": "2019-11-06T02:44:23.000000Z",
                    "updated_at": "2023-12-23T18:10:56.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/noraneko-to-ookami/cover/kTj1R8S5BsDD_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/noraneko-to-ookami/cover/kTj1R8S5BsDD_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/noraneko-to-ookami/cover/kTj1R8S5BsDD_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/noraneko-to-ookami/cover/kTj1R8S5BsDD_thumb.jpg",
                    "href": "https://mangalib.me/noraneko-to-ookami",
                    "title_status_id": null
                },
                {
                    "id": 11445,
                    "name": "Jishou Akuyaku Reijou na Konyakusha no Kansatsu Kiroku",
                    "eng_name": "An Observation Record of my Fiancée - A Self-Proclaimed Villainess",
                    "rus_name": "Дневник наблюдений за моей невестой, провозгласившей себя злодейкой",
                    "cover": "wu4WiXWy6XuY",
                    "slug": "jishou-akuyaku-reijou-na-konyakusha-no-kansatsu-kiroku",
                    "type_id": 1,
                    "created_at": "2019-04-12T08:03:01.000000Z",
                    "updated_at": "2023-12-23T18:14:40.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/jishou-akuyaku-reijou-na-konyakusha-no-kansatsu-kiroku/cover/wu4WiXWy6XuY_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/jishou-akuyaku-reijou-na-konyakusha-no-kansatsu-kiroku/cover/wu4WiXWy6XuY_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/jishou-akuyaku-reijou-na-konyakusha-no-kansatsu-kiroku/cover/wu4WiXWy6XuY_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/jishou-akuyaku-reijou-na-konyakusha-no-kansatsu-kiroku/cover/wu4WiXWy6XuY_thumb.jpg",
                    "href": "https://mangalib.me/jishou-akuyaku-reijou-na-konyakusha-no-kansatsu-kiroku",
                    "title_status_id": null
                },
                {
                    "id": 8567,
                    "name": "Otomege Sekai wa Mob ni Kibishii Sekai Desu",
                    "eng_name": "The World of Otome Games is Tough for Mobs",
                    "rus_name": "Мир отомэ игр — это тяжелый мир для мобов",
                    "cover": "hsiJGowv4Hsq",
                    "slug": "otome-ga-world-is-a-tough-world-for-mob",
                    "type_id": 1,
                    "created_at": "2019-01-04T19:32:20.000000Z",
                    "updated_at": "2023-12-23T18:14:47.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/otome-ga-world-is-a-tough-world-for-mob/cover/hsiJGowv4Hsq_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/otome-ga-world-is-a-tough-world-for-mob/cover/hsiJGowv4Hsq_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/otome-ga-world-is-a-tough-world-for-mob/cover/hsiJGowv4Hsq_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/otome-ga-world-is-a-tough-world-for-mob/cover/hsiJGowv4Hsq_thumb.jpg",
                    "href": "https://mangalib.me/otome-ga-world-is-a-tough-world-for-mob",
                    "title_status_id": null
                },
                {
                    "id": 20906,
                    "name": "Isekai de Cheat Skill wo te ni Shita ore wa, Genjitsu Sekai wo mo Musou Suru ~Level Up wa Jinsei wo Kaeta~",
                    "eng_name": "I Got a Cheat Ability in a Different World, and Became Extraordinary Even in the Real World",
                    "rus_name": "Я получил читерскую способность в другом мире и стал экстраординарным в реальном   ~ повышение уровня изменило мою жизнь~",
                    "cover": "q4gOasqD3s2y",
                    "slug": "isekai-de-cheat-skill-wo-te-ni-shita-ore-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta",
                    "type_id": 1,
                    "created_at": "2020-01-09T11:05:11.000000Z",
                    "updated_at": "2023-12-23T18:13:22.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/isekai-de-cheat-skill-wo-te-ni-shita-ore-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta/cover/q4gOasqD3s2y_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/isekai-de-cheat-skill-wo-te-ni-shita-ore-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta/cover/q4gOasqD3s2y_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/isekai-de-cheat-skill-wo-te-ni-shita-ore-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta/cover/q4gOasqD3s2y_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/isekai-de-cheat-skill-wo-te-ni-shita-ore-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta/cover/q4gOasqD3s2y_thumb.jpg",
                    "href": "https://mangalib.me/isekai-de-cheat-skill-wo-te-ni-shita-ore-wa-genjitsu-sekai-wo-mo-musou-suru-level-up-wa-jinsei-wo-kaeta",
                    "title_status_id": null
                },
                {
                    "id": 12617,
                    "name": "Yamada-kun to Lv999 no Koi wo Suru",
                    "eng_name": "My Lv999 Love for Yamada-kun",
                    "rus_name": "Моя любовь 999 уровня к Ямаде-куну",
                    "cover": "eANVWrLmel9m",
                    "slug": "yamada-kun-to-lv999-no-koi-wo-suru",
                    "type_id": 1,
                    "created_at": "2019-05-24T09:40:23.000000Z",
                    "updated_at": "2023-12-23T18:13:57.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/yamada-kun-to-lv999-no-koi-wo-suru/cover/eANVWrLmel9m_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/yamada-kun-to-lv999-no-koi-wo-suru/cover/eANVWrLmel9m_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/yamada-kun-to-lv999-no-koi-wo-suru/cover/eANVWrLmel9m_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/yamada-kun-to-lv999-no-koi-wo-suru/cover/eANVWrLmel9m_thumb.jpg",
                    "href": "https://mangalib.me/yamada-kun-to-lv999-no-koi-wo-suru",
                    "title_status_id": null
                },
                {
                    "id": 3322,
                    "name": "Tsubaki-chou Lonely Planet",
                    "eng_name": "",
                    "rus_name": "Одинокая планета из квартала Цубаки",
                    "cover": "YGKpaSsP4FTY",
                    "slug": "tsubakichou-lonely-planet",
                    "type_id": 1,
                    "created_at": "2017-10-27T15:34:21.000000Z",
                    "updated_at": "2023-12-23T18:14:56.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/tsubakichou-lonely-planet/cover/YGKpaSsP4FTY_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/tsubakichou-lonely-planet/cover/YGKpaSsP4FTY_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/tsubakichou-lonely-planet/cover/YGKpaSsP4FTY_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/tsubakichou-lonely-planet/cover/YGKpaSsP4FTY_thumb.jpg",
                    "href": "https://mangalib.me/tsubakichou-lonely-planet",
                    "title_status_id": null
                },
                {
                    "id": 21175,
                    "name": "Kimi no koto ga daidaidaidaidai suki na 100-nin no Kanojo",
                    "eng_name": "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You",
                    "rus_name": "100 девушек, которые очень-очень-очень-очень-очень сильно любят тебя",
                    "cover": "1l73txbSO1cy",
                    "slug": "kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi",
                    "type_id": 1,
                    "created_at": "2020-01-13T01:33:17.000000Z",
                    "updated_at": "2023-12-23T18:15:27.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi/cover/1l73txbSO1cy_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi/cover/1l73txbSO1cy_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi/cover/1l73txbSO1cy_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi/cover/1l73txbSO1cy_thumb.jpg",
                    "href": "https://mangalib.me/kimi-no-koto-ga-dai-dai-dai-dai-daisuki-na-100-hito-no-kareshi",
                    "title_status_id": null
                },
                {
                    "id": 4436,
                    "name": "Go-Toubun no Hanayome",
                    "eng_name": "The Quintessential Quintuplets",
                    "rus_name": "Пять невест",
                    "cover": "Ua7mbeFT9As6",
                    "slug": "the-five-wedded-brides",
                    "type_id": 1,
                    "created_at": "2018-06-01T06:34:09.000000Z",
                    "updated_at": "2023-12-23T18:12:10.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/the-five-wedded-brides/cover/Ua7mbeFT9As6_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/the-five-wedded-brides/cover/Ua7mbeFT9As6_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/the-five-wedded-brides/cover/Ua7mbeFT9As6_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/the-five-wedded-brides/cover/Ua7mbeFT9As6_thumb.jpg",
                    "href": "https://mangalib.me/the-five-wedded-brides",
                    "title_status_id": null
                },
                {
                    "id": 105,
                    "name": "Hagane no Renkinjutsushi",
                    "eng_name": "Fullmetal Alchemist",
                    "rus_name": "Стальной алхимик",
                    "cover": "KRnP5xAZ6Uts",
                    "slug": "fullmetal_alchemist",
                    "type_id": 1,
                    "created_at": "2016-05-24T11:43:32.000000Z",
                    "updated_at": "2023-12-23T18:14:20.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/fullmetal_alchemist/cover/KRnP5xAZ6Uts_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/fullmetal_alchemist/cover/KRnP5xAZ6Uts_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/fullmetal_alchemist/cover/KRnP5xAZ6Uts_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/fullmetal_alchemist/cover/KRnP5xAZ6Uts_thumb.jpg",
                    "href": "https://mangalib.me/fullmetal_alchemist",
                    "title_status_id": null
                },
                {
                    "id": 32091,
                    "name": "Isekai ni kyuseishu to shite yoba remashitaga, arasa ni wa murinanode, hissori bukku kafe hajimemashita",
                    "eng_name": "The Savior's Book Café in Another World",
                    "rus_name": "Книжное кафе Спасительницы из другого мира",
                    "cover": "S1Z3XVWg3PE2",
                    "slug": "isekai-ni-kyuseishu-to-shite-yoba-remashitaga-arasa-ni-wa-murinanode-hissori-book-cafe-kajimemashita",
                    "type_id": 1,
                    "created_at": "2020-05-09T06:12:30.000000Z",
                    "updated_at": "2023-12-23T18:15:28.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/isekai-ni-kyuseishu-to-shite-yoba-remashitaga-arasa-ni-wa-murinanode-hissori-book-cafe-kajimemashita/cover/S1Z3XVWg3PE2_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/isekai-ni-kyuseishu-to-shite-yoba-remashitaga-arasa-ni-wa-murinanode-hissori-book-cafe-kajimemashita/cover/S1Z3XVWg3PE2_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/isekai-ni-kyuseishu-to-shite-yoba-remashitaga-arasa-ni-wa-murinanode-hissori-book-cafe-kajimemashita/cover/S1Z3XVWg3PE2_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/isekai-ni-kyuseishu-to-shite-yoba-remashitaga-arasa-ni-wa-murinanode-hissori-book-cafe-kajimemashita/cover/S1Z3XVWg3PE2_thumb.jpg",
                    "href": "https://mangalib.me/isekai-ni-kyuseishu-to-shite-yoba-remashitaga-arasa-ni-wa-murinanode-hissori-book-cafe-kajimemashita",
                    "title_status_id": null
                },
                {
                    "id": 3272,
                    "name": "Suijin no Hanayome",
                    "eng_name": "The Water Dragon's Bride",
                    "rus_name": "Невеста бога воды",
                    "cover": "64XAE2dXeUjv",
                    "slug": "suijin-no-hanayome",
                    "type_id": 1,
                    "created_at": "2017-10-26T17:50:42.000000Z",
                    "updated_at": "2023-12-23T18:14:20.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/suijin-no-hanayome/cover/64XAE2dXeUjv_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/suijin-no-hanayome/cover/64XAE2dXeUjv_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/suijin-no-hanayome/cover/64XAE2dXeUjv_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/suijin-no-hanayome/cover/64XAE2dXeUjv_thumb.jpg",
                    "href": "https://mangalib.me/suijin-no-hanayome",
                    "title_status_id": null
                },
                {
                    "id": 122202,
                    "name": "Super no Ura de Yani Suu Hanashi",
                    "eng_name": "A Story About Smoking at the Back of the Supermarket",
                    "rus_name": "История о перекуре за супермаркетом",
                    "cover": "mpnK8Kj3kDLF",
                    "slug": "suupaa-no-ura-yani-suu-hanashi",
                    "type_id": 1,
                    "created_at": "2022-04-04T07:16:04.000000Z",
                    "updated_at": "2023-12-23T18:15:18.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/suupaa-no-ura-yani-suu-hanashi/cover/mpnK8Kj3kDLF_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/suupaa-no-ura-yani-suu-hanashi/cover/mpnK8Kj3kDLF_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/suupaa-no-ura-yani-suu-hanashi/cover/mpnK8Kj3kDLF_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/suupaa-no-ura-yani-suu-hanashi/cover/mpnK8Kj3kDLF_thumb.jpg",
                    "href": "https://mangalib.me/suupaa-no-ura-yani-suu-hanashi",
                    "title_status_id": null
                },
                {
                    "id": 70510,
                    "name": "Dandadan",
                    "eng_name": "Dandadan",
                    "rus_name": "Дандадан",
                    "cover": "OyhdT7MnuYyD",
                    "slug": "dandadan",
                    "type_id": 1,
                    "created_at": "2021-04-05T18:14:51.000000Z",
                    "updated_at": "2023-12-23T18:14:30.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/dandadan/cover/OyhdT7MnuYyD_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/dandadan/cover/OyhdT7MnuYyD_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/dandadan/cover/OyhdT7MnuYyD_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/dandadan/cover/OyhdT7MnuYyD_thumb.jpg",
                    "href": "https://mangalib.me/dandadan",
                    "title_status_id": null
                },
                {
                    "id": 7666,
                    "name": "Kimi ga Kirai na Koi no Hanashi",
                    "eng_name": "A Story of an Unlikely Love",
                    "rus_name": "История о маловероятной любви",
                    "cover": "ok3DpYpuwSyt",
                    "slug": "kimi-ga-kirai-na-koi-no-hanashi",
                    "type_id": 1,
                    "created_at": "2018-11-20T12:41:01.000000Z",
                    "updated_at": "2023-12-23T18:15:17.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kimi-ga-kirai-na-koi-no-hanashi/cover/ok3DpYpuwSyt_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kimi-ga-kirai-na-koi-no-hanashi/cover/ok3DpYpuwSyt_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kimi-ga-kirai-na-koi-no-hanashi/cover/ok3DpYpuwSyt_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kimi-ga-kirai-na-koi-no-hanashi/cover/ok3DpYpuwSyt_thumb.jpg",
                    "href": "https://mangalib.me/kimi-ga-kirai-na-koi-no-hanashi",
                    "title_status_id": null
                },
                {
                    "id": 9525,
                    "name": "Lv2 kara Cheat datta Moto Yuusha Kouho no Mattari Isekai Life",
                    "eng_name": "The Laid-back Life in Another World of the Ex-Hero Candidate Who Turned out to be a Cheat from Level 2",
                    "rus_name": "Непринужденная жизнь в другом мире экс-кандидата в герои, оказавшегося читером со 2 уровня",
                    "cover": "0NNzCUEHw1Bn",
                    "slug": "lv2-kara-cheat-datta-moto-yuusha-kouho-no-mattari-isekai-life",
                    "type_id": 1,
                    "created_at": "2019-02-10T10:06:39.000000Z",
                    "updated_at": "2023-12-23T18:10:41.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/lv2-kara-cheat-datta-moto-yuusha-kouho-no-mattari-isekai-life/cover/0NNzCUEHw1Bn_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/lv2-kara-cheat-datta-moto-yuusha-kouho-no-mattari-isekai-life/cover/0NNzCUEHw1Bn_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/lv2-kara-cheat-datta-moto-yuusha-kouho-no-mattari-isekai-life/cover/0NNzCUEHw1Bn_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/lv2-kara-cheat-datta-moto-yuusha-kouho-no-mattari-isekai-life/cover/0NNzCUEHw1Bn_thumb.jpg",
                    "href": "https://mangalib.me/lv2-kara-cheat-datta-moto-yuusha-kouho-no-mattari-isekai-life",
                    "title_status_id": null
                },
                {
                    "id": 2198,
                    "name": "Tate no Yuusha no Nariagari",
                    "eng_name": "The Rising of the Shield Hero",
                    "rus_name": "Восхождение Героя Щита",
                    "cover": "0oXepohxgmJB",
                    "slug": "tate-no-yuusha-no-nariagari",
                    "type_id": 1,
                    "created_at": "2017-04-07T13:24:01.000000Z",
                    "updated_at": "2023-12-23T18:14:24.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/tate-no-yuusha-no-nariagari/cover/0oXepohxgmJB_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/tate-no-yuusha-no-nariagari/cover/0oXepohxgmJB_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/tate-no-yuusha-no-nariagari/cover/0oXepohxgmJB_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/tate-no-yuusha-no-nariagari/cover/0oXepohxgmJB_thumb.jpg",
                    "href": "https://mangalib.me/tate-no-yuusha-no-nariagari",
                    "title_status_id": null
                },
                {
                    "id": 1572,
                    "name": "JoJo no Kimyou na Bouken Part 7: Sutiru Boru Ran",
                    "eng_name": "JoJo's Bizarre Adventure – Part 7: Steel Ball Run",
                    "rus_name": "Невероятные Приключения ДжоДжо — Часть 7: Стил-Болл-Ран",
                    "cover": "baa6aqWiEAQ8",
                    "slug": "steel-ball-run",
                    "type_id": 1,
                    "created_at": "2016-10-04T08:35:19.000000Z",
                    "updated_at": "2023-12-23T18:03:19.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/steel-ball-run/cover/baa6aqWiEAQ8_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/steel-ball-run/cover/baa6aqWiEAQ8_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/steel-ball-run/cover/baa6aqWiEAQ8_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/steel-ball-run/cover/baa6aqWiEAQ8_thumb.jpg",
                    "href": "https://mangalib.me/steel-ball-run",
                    "title_status_id": null
                },
                {
                    "id": 94954,
                    "name": "Boroboro no Elf-san wo Shiawaseni suru Kusuriuri-san",
                    "eng_name": "The Apothecary Will Make This Battered Elf Happy",
                    "rus_name": "Фармацевт осчастливит эту избитую Эльфийку",
                    "cover": "wwyNjwjHjiu5",
                    "slug": "boroboro-no-erufu-san-o-shiawaseni-suru-kusuri-uri-sa-n",
                    "type_id": 1,
                    "created_at": "2021-09-12T19:09:41.000000Z",
                    "updated_at": "2023-12-23T18:11:58.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/boroboro-no-erufu-san-o-shiawaseni-suru-kusuri-uri-sa-n/cover/wwyNjwjHjiu5_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/boroboro-no-erufu-san-o-shiawaseni-suru-kusuri-uri-sa-n/cover/wwyNjwjHjiu5_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/boroboro-no-erufu-san-o-shiawaseni-suru-kusuri-uri-sa-n/cover/wwyNjwjHjiu5_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/boroboro-no-erufu-san-o-shiawaseni-suru-kusuri-uri-sa-n/cover/wwyNjwjHjiu5_thumb.jpg",
                    "href": "https://mangalib.me/boroboro-no-erufu-san-o-shiawaseni-suru-kusuri-uri-sa-n",
                    "title_status_id": null
                },
                {
                    "id": 28795,
                    "name": "Kindan Shitei de Breakthrough ~ Yuusha no Musuko ga Maou no Deshi de Nani ga Warui ~",
                    "eng_name": "A Breakthrough Brought by Forbidden Master and Disciple",
                    "rus_name": "Прорыв с запретным мастером",
                    "cover": "VvWmFSWNLs9u",
                    "slug": "kindan-shitei-de-breakthrough-yuusha-no-musuko-ga-maou-no-deshi-de-nani-ga-warui",
                    "type_id": 1,
                    "created_at": "2020-04-15T10:02:35.000000Z",
                    "updated_at": "2023-12-23T18:13:09.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kindan-shitei-de-breakthrough-yuusha-no-musuko-ga-maou-no-deshi-de-nani-ga-warui/cover/VvWmFSWNLs9u_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kindan-shitei-de-breakthrough-yuusha-no-musuko-ga-maou-no-deshi-de-nani-ga-warui/cover/VvWmFSWNLs9u_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kindan-shitei-de-breakthrough-yuusha-no-musuko-ga-maou-no-deshi-de-nani-ga-warui/cover/VvWmFSWNLs9u_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kindan-shitei-de-breakthrough-yuusha-no-musuko-ga-maou-no-deshi-de-nani-ga-warui/cover/VvWmFSWNLs9u_thumb.jpg",
                    "href": "https://mangalib.me/kindan-shitei-de-breakthrough-yuusha-no-musuko-ga-maou-no-deshi-de-nani-ga-warui",
                    "title_status_id": null
                },
                {
                    "id": 9493,
                    "name": "Sekai Saikyou no Assassin, isekai kizoku ni tensei suru",
                    "eng_name": "The World's Best Assassin, Reincarnated in a Different World as an Aristocrat",
                    "rus_name": "Лучший в мире ассасин, переродившийся в другом мире как аристократ",
                    "cover": "YuWKbF7LGsHG",
                    "slug": "the-worlds-best-assassin-reincarnated-in-a-different-world-as-an-aristocrat",
                    "type_id": 1,
                    "created_at": "2019-02-09T10:10:46.000000Z",
                    "updated_at": "2023-12-23T18:14:11.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/the-worlds-best-assassin-reincarnated-in-a-different-world-as-an-aristocrat/cover/YuWKbF7LGsHG_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/the-worlds-best-assassin-reincarnated-in-a-different-world-as-an-aristocrat/cover/YuWKbF7LGsHG_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/the-worlds-best-assassin-reincarnated-in-a-different-world-as-an-aristocrat/cover/YuWKbF7LGsHG_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/the-worlds-best-assassin-reincarnated-in-a-different-world-as-an-aristocrat/cover/YuWKbF7LGsHG_thumb.jpg",
                    "href": "https://mangalib.me/the-worlds-best-assassin-reincarnated-in-a-different-world-as-an-aristocrat",
                    "title_status_id": null
                },
                {
                    "id": 43802,
                    "name": "Kamibukuro-kun wa Koishiteru",
                    "eng_name": "Paperbag-kun Is in Love",
                    "rus_name": "Бумажный пакетик-кун влюблён",
                    "cover": "kjvKPoicRwYr",
                    "slug": "kamibukuro-kun-wa-koishiteru",
                    "type_id": 1,
                    "created_at": "2020-08-13T06:29:54.000000Z",
                    "updated_at": "2023-12-23T17:56:57.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kamibukuro-kun-wa-koishiteru/cover/kjvKPoicRwYr_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kamibukuro-kun-wa-koishiteru/cover/kjvKPoicRwYr_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kamibukuro-kun-wa-koishiteru/cover/kjvKPoicRwYr_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kamibukuro-kun-wa-koishiteru/cover/kjvKPoicRwYr_thumb.jpg",
                    "href": "https://mangalib.me/kamibukuro-kun-wa-koishiteru",
                    "title_status_id": null
                },
                {
                    "id": 91643,
                    "name": "JoJo no Kimyou na Bouken Part 9: The JoJoLands",
                    "eng_name": "JoJo's Bizarre Adventure Part 9: The JoJoLands",
                    "rus_name": "Невероятные приключения ДжоДжо — Часть 9: ДжоДжоЛендс",
                    "cover": "saaFaLXLUDBe",
                    "slug": "jojo-lands",
                    "type_id": 1,
                    "created_at": "2021-08-17T10:48:51.000000Z",
                    "updated_at": "2023-12-23T18:15:06.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/jojo-lands/cover/saaFaLXLUDBe_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/jojo-lands/cover/saaFaLXLUDBe_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/jojo-lands/cover/saaFaLXLUDBe_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/jojo-lands/cover/saaFaLXLUDBe_thumb.jpg",
                    "href": "https://mangalib.me/jojo-lands",
                    "title_status_id": null
                },
                {
                    "id": 1300,
                    "name": "Namaikizakari",
                    "eng_name": "His Cheekiness is in Full Bloom",
                    "rus_name": "Идеальная парочка",
                    "cover": "yFSnw5f4kcB5",
                    "slug": "namaikizakari",
                    "type_id": 1,
                    "created_at": "2016-07-27T09:56:04.000000Z",
                    "updated_at": "2023-12-23T18:15:27.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/namaikizakari/cover/yFSnw5f4kcB5_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/namaikizakari/cover/yFSnw5f4kcB5_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/namaikizakari/cover/yFSnw5f4kcB5_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/namaikizakari/cover/yFSnw5f4kcB5_thumb.jpg",
                    "href": "https://mangalib.me/namaikizakari",
                    "title_status_id": null
                },
                {
                    "id": 1573,
                    "name": "JoJo no Kimyou na Bouken Sono 8: JoJolion",
                    "eng_name": "JoJo's Bizarre Adventure — Part 8: JoJolion",
                    "rus_name": "Невероятные Приключения ДжоДжо — Часть 8: ДжоДжолион",
                    "cover": "AVcqita6Ml7W",
                    "slug": "jojo-no-kimyou-na-bouken-jojorion",
                    "type_id": 1,
                    "created_at": "2016-10-04T09:32:50.000000Z",
                    "updated_at": "2023-12-23T18:14:28.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/jojo-no-kimyou-na-bouken-jojorion/cover/AVcqita6Ml7W_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/jojo-no-kimyou-na-bouken-jojorion/cover/AVcqita6Ml7W_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/jojo-no-kimyou-na-bouken-jojorion/cover/AVcqita6Ml7W_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/jojo-no-kimyou-na-bouken-jojorion/cover/AVcqita6Ml7W_thumb.jpg",
                    "href": "https://mangalib.me/jojo-no-kimyou-na-bouken-jojorion",
                    "title_status_id": null
                },
                {
                    "id": 5118,
                    "name": "Feari Teiru: Hyaku-nen Kuesuto",
                    "eng_name": "Fairy Tail: 100 Years Quest",
                    "rus_name": "Хвост Феи: 100-летний квест",
                    "cover": "qiZOB4exfRbt",
                    "slug": "fairy-tail-100-years-quest",
                    "type_id": 1,
                    "created_at": "2018-07-25T13:16:06.000000Z",
                    "updated_at": "2023-12-23T18:15:22.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/fairy-tail-100-years-quest/cover/qiZOB4exfRbt_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/fairy-tail-100-years-quest/cover/qiZOB4exfRbt_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/fairy-tail-100-years-quest/cover/qiZOB4exfRbt_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/fairy-tail-100-years-quest/cover/qiZOB4exfRbt_thumb.jpg",
                    "href": "https://mangalib.me/fairy-tail-100-years-quest",
                    "title_status_id": null
                },
                {
                    "id": 100,
                    "name": "Fairy Tail",
                    "eng_name": "Fairy Tail",
                    "rus_name": "Хвост Феи",
                    "cover": "xS7ii7I5xmW1",
                    "slug": "fairy-tail",
                    "type_id": 1,
                    "created_at": "2016-05-24T09:57:00.000000Z",
                    "updated_at": "2023-12-23T18:13:58.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/fairy-tail/cover/xS7ii7I5xmW1_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/fairy-tail/cover/xS7ii7I5xmW1_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/fairy-tail/cover/xS7ii7I5xmW1_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/fairy-tail/cover/xS7ii7I5xmW1_thumb.jpg",
                    "href": "https://mangalib.me/fairy-tail",
                    "title_status_id": null
                },
                {
                    "id": 5430,
                    "name": "Maou ni Natta node, Dungeon Tsukutte Jingai Musume to Honobono suru",
                    "eng_name": "I Became the Demon Lord so I Created a Dungeon and Spend Heartwarming Time There with Non-Human Girls",
                    "rus_name": "Я стал Повелителем Демонов и создал подземелье, чтобы проводить время с девушками-монстрами",
                    "cover": "aGPGD2o2jCmi",
                    "slug": "maou-ni-natta-node-dungeon-tsukutte-jingai-musume-to-honobono-suru",
                    "type_id": 1,
                    "created_at": "2018-08-04T08:58:14.000000Z",
                    "updated_at": "2023-12-23T18:14:06.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/maou-ni-natta-node-dungeon-tsukutte-jingai-musume-to-honobono-suru/cover/aGPGD2o2jCmi_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/maou-ni-natta-node-dungeon-tsukutte-jingai-musume-to-honobono-suru/cover/aGPGD2o2jCmi_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/maou-ni-natta-node-dungeon-tsukutte-jingai-musume-to-honobono-suru/cover/aGPGD2o2jCmi_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/maou-ni-natta-node-dungeon-tsukutte-jingai-musume-to-honobono-suru/cover/aGPGD2o2jCmi_thumb.jpg",
                    "href": "https://mangalib.me/maou-ni-natta-node-dungeon-tsukutte-jingai-musume-to-honobono-suru",
                    "title_status_id": null
                },
                {
                    "id": 1284,
                    "name": "ReLIFE",
                    "eng_name": "ReLIFE",
                    "rus_name": "Повторная жизнь",
                    "cover": "hHsr4TBif5yD",
                    "slug": "relife",
                    "type_id": 1,
                    "created_at": "2016-07-03T20:46:37.000000Z",
                    "updated_at": "2023-12-23T18:14:51.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/relife/cover/hHsr4TBif5yD_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/relife/cover/hHsr4TBif5yD_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/relife/cover/hHsr4TBif5yD_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/relife/cover/hHsr4TBif5yD_thumb.jpg",
                    "href": "https://mangalib.me/relife",
                    "title_status_id": null
                },
                {
                    "id": 14386,
                    "name": "Yubisaki to Renren",
                    "eng_name": "Attached to Your Fingertips",
                    "rus_name": "Любовь с кончиков пальцев",
                    "cover": "pWZm40qOGu0U",
                    "slug": "yubisaki-to-renren",
                    "type_id": 1,
                    "created_at": "2019-07-22T08:22:03.000000Z",
                    "updated_at": "2023-12-23T18:13:26.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/yubisaki-to-renren/cover/pWZm40qOGu0U_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/yubisaki-to-renren/cover/pWZm40qOGu0U_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/yubisaki-to-renren/cover/pWZm40qOGu0U_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/yubisaki-to-renren/cover/pWZm40qOGu0U_thumb.jpg",
                    "href": "https://mangalib.me/yubisaki-to-renren",
                    "title_status_id": null
                },
                {
                    "id": 13158,
                    "name": "Ookami wa Nemuranai",
                    "eng_name": "The Wolf Won't Sleep",
                    "rus_name": "Волк не дремлет",
                    "cover": "LjNByP6ZpIUj",
                    "slug": "the-wolf-wont-sleep",
                    "type_id": 1,
                    "created_at": "2019-06-11T17:51:20.000000Z",
                    "updated_at": "2023-12-23T18:12:31.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/the-wolf-wont-sleep/cover/LjNByP6ZpIUj_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/the-wolf-wont-sleep/cover/LjNByP6ZpIUj_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/the-wolf-wont-sleep/cover/LjNByP6ZpIUj_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/the-wolf-wont-sleep/cover/LjNByP6ZpIUj_thumb.jpg",
                    "href": "https://mangalib.me/the-wolf-wont-sleep",
                    "title_status_id": null
                },
                {
                    "id": 135514,
                    "name": "1-Nichi-goto ni tsun ga hette ku tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere joshi",
                    "eng_name": "The Tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere Girl Getting Less and Less Tsun Day by Day",
                    "rus_name": "Цунцунцунцунцунцунцунцунцунцунцундере с каждым днём становится всё меньше цун",
                    "cover": "oq6UPwJ5tArO",
                    "slug": "1-nichi-goto-ni-tsun-ga-hette-ku-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-joshi",
                    "type_id": 1,
                    "created_at": "2022-07-15T12:47:35.000000Z",
                    "updated_at": "2023-12-23T18:15:14.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/1-nichi-goto-ni-tsun-ga-hette-ku-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-joshi/cover/oq6UPwJ5tArO_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/1-nichi-goto-ni-tsun-ga-hette-ku-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-joshi/cover/oq6UPwJ5tArO_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/1-nichi-goto-ni-tsun-ga-hette-ku-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-joshi/cover/oq6UPwJ5tArO_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/1-nichi-goto-ni-tsun-ga-hette-ku-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-joshi/cover/oq6UPwJ5tArO_thumb.jpg",
                    "href": "https://mangalib.me/1-nichi-goto-ni-tsun-ga-hette-ku-tsuntsuntsuntsuntsuntsuntsuntsuntsuntsuntsundere-joshi",
                    "title_status_id": null
                },
                {
                    "id": 23270,
                    "name": "Akuyaku Reijou Reberu 99 ~Watashi wa UraBOSU desuga Maou de wa arimasen~",
                    "eng_name": "Villainess Level 99 ~I may be the Hidden Boss but I'm not the Demon Lord~",
                    "rus_name": "Злодейка 99 уровня: Я могу быть скрытым боссом, но я не Король демонов",
                    "cover": "2IZNhcVjQGjn",
                    "slug": "akuyaku-reijou-reberu-99-watashi-wa-urabosu-desuga-maou-de-wa-arimasen",
                    "type_id": 1,
                    "created_at": "2020-02-11T04:55:27.000000Z",
                    "updated_at": "2023-12-23T18:15:34.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/akuyaku-reijou-reberu-99-watashi-wa-urabosu-desuga-maou-de-wa-arimasen/cover/2IZNhcVjQGjn_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/akuyaku-reijou-reberu-99-watashi-wa-urabosu-desuga-maou-de-wa-arimasen/cover/2IZNhcVjQGjn_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/akuyaku-reijou-reberu-99-watashi-wa-urabosu-desuga-maou-de-wa-arimasen/cover/2IZNhcVjQGjn_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/akuyaku-reijou-reberu-99-watashi-wa-urabosu-desuga-maou-de-wa-arimasen/cover/2IZNhcVjQGjn_thumb.jpg",
                    "href": "https://mangalib.me/akuyaku-reijou-reberu-99-watashi-wa-urabosu-desuga-maou-de-wa-arimasen",
                    "title_status_id": null
                },
                {
                    "id": 4793,
                    "name": "Otome Game no Hametsu Flag shika nai Akuyaku Reijou ni Tensei shite shimatta…",
                    "eng_name": "I Reincarnated into an Otome Game as a Villainess With Only Destruction Flags…",
                    "rus_name": "Моя реинкарнация в отомэ-игру в качестве главной злодейки",
                    "cover": "Cv6DldeP62Zq",
                    "slug": "i-reincarnated-into-an-otome-game-as-a-villainess-with-only-destruction-flags",
                    "type_id": 1,
                    "created_at": "2018-07-11T03:09:45.000000Z",
                    "updated_at": "2023-12-23T18:10:40.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/i-reincarnated-into-an-otome-game-as-a-villainess-with-only-destruction-flags/cover/Cv6DldeP62Zq_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/i-reincarnated-into-an-otome-game-as-a-villainess-with-only-destruction-flags/cover/Cv6DldeP62Zq_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/i-reincarnated-into-an-otome-game-as-a-villainess-with-only-destruction-flags/cover/Cv6DldeP62Zq_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/i-reincarnated-into-an-otome-game-as-a-villainess-with-only-destruction-flags/cover/Cv6DldeP62Zq_thumb.jpg",
                    "href": "https://mangalib.me/i-reincarnated-into-an-otome-game-as-a-villainess-with-only-destruction-flags",
                    "title_status_id": null
                },
                {
                    "id": 5587,
                    "name": "Raise wa Tanin ga Ii",
                    "eng_name": "An Outsider Is Better in the Afterlife",
                    "rus_name": "Незнакомцы в другой жизни",
                    "cover": "bQdYPEDCDBuF",
                    "slug": "raise-wa-tanin-ga-ii",
                    "type_id": 1,
                    "created_at": "2018-08-11T16:32:33.000000Z",
                    "updated_at": "2023-12-23T18:10:38.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/raise-wa-tanin-ga-ii/cover/bQdYPEDCDBuF_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/raise-wa-tanin-ga-ii/cover/bQdYPEDCDBuF_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/raise-wa-tanin-ga-ii/cover/bQdYPEDCDBuF_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/raise-wa-tanin-ga-ii/cover/bQdYPEDCDBuF_thumb.jpg",
                    "href": "https://mangalib.me/raise-wa-tanin-ga-ii",
                    "title_status_id": null
                },
                {
                    "id": 2012,
                    "name": "Kokou no Hito",
                    "eng_name": "The Climber",
                    "rus_name": "Скалолаз",
                    "cover": "b8CjXSxEftX4",
                    "slug": "kokou-no-hito",
                    "type_id": 1,
                    "created_at": "2017-02-24T10:25:48.000000Z",
                    "updated_at": "2023-12-23T18:14:28.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kokou-no-hito/cover/b8CjXSxEftX4_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kokou-no-hito/cover/b8CjXSxEftX4_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kokou-no-hito/cover/b8CjXSxEftX4_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kokou-no-hito/cover/b8CjXSxEftX4_thumb.jpg",
                    "href": "https://mangalib.me/kokou-no-hito",
                    "title_status_id": null
                },
                {
                    "id": 8547,
                    "name": "Sachi-iro no One Room",
                    "eng_name": "One Room of Happiness",
                    "rus_name": "Цвета счастья в одной комнате",
                    "cover": "GEYuEzfVWM0P",
                    "slug": "sachi-iro-no-one-room",
                    "type_id": 1,
                    "created_at": "2019-01-04T04:04:52.000000Z",
                    "updated_at": "2023-12-23T18:15:13.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/sachi-iro-no-one-room/cover/GEYuEzfVWM0P_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/sachi-iro-no-one-room/cover/GEYuEzfVWM0P_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/sachi-iro-no-one-room/cover/GEYuEzfVWM0P_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/sachi-iro-no-one-room/cover/GEYuEzfVWM0P_thumb.jpg",
                    "href": "https://mangalib.me/sachi-iro-no-one-room",
                    "title_status_id": null
                },
                {
                    "id": 40941,
                    "name": "Uruwashi no yoi tsuki",
                    "eng_name": "In the clear moonlit dusk",
                    "rus_name": "Прекрасная вечерняя луна",
                    "cover": "XYUPItjxkT4D",
                    "slug": "uruwashi-no-yoi-tsuki",
                    "type_id": 1,
                    "created_at": "2020-07-20T11:27:00.000000Z",
                    "updated_at": "2023-12-23T18:14:01.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/uruwashi-no-yoi-tsuki/cover/XYUPItjxkT4D_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/uruwashi-no-yoi-tsuki/cover/XYUPItjxkT4D_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/uruwashi-no-yoi-tsuki/cover/XYUPItjxkT4D_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/uruwashi-no-yoi-tsuki/cover/XYUPItjxkT4D_thumb.jpg",
                    "href": "https://mangalib.me/uruwashi-no-yoi-tsuki",
                    "title_status_id": null
                },
                {
                    "id": 1598,
                    "name": "Pandora Hearts",
                    "eng_name": "Pandora Hearts",
                    "rus_name": "Сердца Пандоры",
                    "cover": "1ZVzs1BWxEQ7",
                    "slug": "pandora-hearts",
                    "type_id": 1,
                    "created_at": "2016-10-18T11:14:35.000000Z",
                    "updated_at": "2023-12-23T18:15:27.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/pandora-hearts/cover/1ZVzs1BWxEQ7_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/pandora-hearts/cover/1ZVzs1BWxEQ7_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/pandora-hearts/cover/1ZVzs1BWxEQ7_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/pandora-hearts/cover/1ZVzs1BWxEQ7_thumb.jpg",
                    "href": "https://mangalib.me/pandora-hearts",
                    "title_status_id": null
                },
                {
                    "id": 2895,
                    "name": "Tomo-chan wa Onnanoko!",
                    "eng_name": "Tomo-chan is a girl!",
                    "rus_name": "Томо-тян – девушка!",
                    "cover": "nzW7aYthFQfh",
                    "slug": "tomochan-wa-onnanoko",
                    "type_id": 1,
                    "created_at": "2017-07-21T19:17:52.000000Z",
                    "updated_at": "2023-12-23T18:11:45.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/tomochan-wa-onnanoko/cover/nzW7aYthFQfh_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/tomochan-wa-onnanoko/cover/nzW7aYthFQfh_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/tomochan-wa-onnanoko/cover/nzW7aYthFQfh_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/tomochan-wa-onnanoko/cover/nzW7aYthFQfh_thumb.jpg",
                    "href": "https://mangalib.me/tomochan-wa-onnanoko",
                    "title_status_id": null
                },
                {
                    "id": 1061,
                    "name": "Abarabone no Onna",
                    "eng_name": "Ribs Woman",
                    "rus_name": "Женщина и рёбра",
                    "cover": "ZcWNFh83umXr",
                    "slug": "ribs-woman",
                    "type_id": 1,
                    "created_at": "2016-06-10T06:57:58.000000Z",
                    "updated_at": "2023-12-23T17:25:24.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/ribs-woman/cover/ZcWNFh83umXr_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/ribs-woman/cover/ZcWNFh83umXr_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/ribs-woman/cover/ZcWNFh83umXr_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/ribs-woman/cover/ZcWNFh83umXr_thumb.jpg",
                    "href": "https://mangalib.me/ribs-woman",
                    "title_status_id": null
                },
                {
                    "id": 24681,
                    "name": "Kaette kudasai! Akutsu-san",
                    "eng_name": "Please,Go Home, Akutsu-san!",
                    "rus_name": "Пожалуйста, иди домой, Акуцу-сан!",
                    "cover": "eSmibZ3jPJm8",
                    "slug": "kaette-kudasai-akutsu-san",
                    "type_id": 1,
                    "created_at": "2020-03-02T10:17:17.000000Z",
                    "updated_at": "2023-12-23T18:15:18.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/kaette-kudasai-akutsu-san/cover/eSmibZ3jPJm8_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/kaette-kudasai-akutsu-san/cover/eSmibZ3jPJm8_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/kaette-kudasai-akutsu-san/cover/eSmibZ3jPJm8_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/kaette-kudasai-akutsu-san/cover/eSmibZ3jPJm8_thumb.jpg",
                    "href": "https://mangalib.me/kaette-kudasai-akutsu-san",
                    "title_status_id": null
                },
                {
                    "id": 156325,
                    "name": "Hotaru no Yomeiri",
                    "eng_name": "Wedding of Fireflies",
                    "rus_name": "Свадьба светлячков",
                    "cover": "yI8B8ix2e4EI",
                    "slug": "hotaru-no-yomeiri",
                    "type_id": 1,
                    "created_at": "2023-01-24T17:32:49.000000Z",
                    "updated_at": "2023-12-23T18:15:16.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/hotaru-no-yomeiri/cover/yI8B8ix2e4EI_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/hotaru-no-yomeiri/cover/yI8B8ix2e4EI_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/hotaru-no-yomeiri/cover/yI8B8ix2e4EI_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/hotaru-no-yomeiri/cover/yI8B8ix2e4EI_thumb.jpg",
                    "href": "https://mangalib.me/hotaru-no-yomeiri",
                    "title_status_id": null
                },
                {
                    "id": 47835,
                    "name": "Banana Fish. Hikari no niwa",
                    "eng_name": "Banana Fish. Garden of light.",
                    "rus_name": "Банановая рыба. Экстры!",
                    "cover": "7tSW1SXzWiHH",
                    "slug": "banana-fish-garden-of-light",
                    "type_id": 1,
                    "created_at": "2020-09-19T15:16:30.000000Z",
                    "updated_at": "2023-12-23T18:09:58.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/banana-fish-garden-of-light/cover/7tSW1SXzWiHH_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/banana-fish-garden-of-light/cover/7tSW1SXzWiHH_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/banana-fish-garden-of-light/cover/7tSW1SXzWiHH_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/banana-fish-garden-of-light/cover/7tSW1SXzWiHH_thumb.jpg",
                    "href": "https://mangalib.me/banana-fish-garden-of-light",
                    "title_status_id": null
                },
                {
                    "id": 131974,
                    "name": "Just Listen to the Song",
                    "eng_name": "Just Listen to the Song",
                    "rus_name": "Просто послушай",
                    "cover": "0PHfpE1u1M3Z",
                    "slug": "listen-to-futu",
                    "type_id": 1,
                    "created_at": "2022-06-19T15:37:32.000000Z",
                    "updated_at": "2023-12-23T18:09:19.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/listen-to-futu/cover/0PHfpE1u1M3Z_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/listen-to-futu/cover/0PHfpE1u1M3Z_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/listen-to-futu/cover/0PHfpE1u1M3Z_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/listen-to-futu/cover/0PHfpE1u1M3Z_thumb.jpg",
                    "href": "https://mangalib.me/listen-to-futu",
                    "title_status_id": null
                },
                {
                    "id": 63275,
                    "name": "SK8 esukeeito",
                    "eng_name": "SK8 the Infinity",
                    "rus_name": "Скейт: Бесконечность",
                    "cover": "EUgiCiqUJY4R",
                    "slug": "sk8-esukeeito",
                    "type_id": 1,
                    "created_at": "2021-02-08T15:19:53.000000Z",
                    "updated_at": "2023-12-23T18:12:58.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/sk8-esukeeito/cover/EUgiCiqUJY4R_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/sk8-esukeeito/cover/EUgiCiqUJY4R_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/sk8-esukeeito/cover/EUgiCiqUJY4R_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/sk8-esukeeito/cover/EUgiCiqUJY4R_thumb.jpg",
                    "href": "https://mangalib.me/sk8-esukeeito",
                    "title_status_id": null
                },
                {
                    "id": 12040,
                    "name": "Isekai de Saikyou Maou no Kodomo-tachi Juunin no Mama ni Nacchaimashita",
                    "eng_name": "I Became the Mother of the Strongest Demon Lord's 10 Children in Another World",
                    "rus_name": "Я стала мамой десяти детей сильнейшего демона в другом мире",
                    "cover": "OV5b0DZacOzH",
                    "slug": "isekai-de-saikyo-mao-no-kodomotachi-no-mama-ni-natchaimashita",
                    "type_id": 1,
                    "created_at": "2019-05-02T15:16:36.000000Z",
                    "updated_at": "2023-12-23T18:15:07.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/isekai-de-saikyo-mao-no-kodomotachi-no-mama-ni-natchaimashita/cover/OV5b0DZacOzH_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/isekai-de-saikyo-mao-no-kodomotachi-no-mama-ni-natchaimashita/cover/OV5b0DZacOzH_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/isekai-de-saikyo-mao-no-kodomotachi-no-mama-ni-natchaimashita/cover/OV5b0DZacOzH_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/isekai-de-saikyo-mao-no-kodomotachi-no-mama-ni-natchaimashita/cover/OV5b0DZacOzH_thumb.jpg",
                    "href": "https://mangalib.me/isekai-de-saikyo-mao-no-kodomotachi-no-mama-ni-natchaimashita",
                    "title_status_id": null
                },
                {
                    "id": 15623,
                    "name": "Sekai O Sai Kochiku",
                    "eng_name": "Rebuild World",
                    "rus_name": "Перестрой мир",
                    "cover": "eSqdpn5Gkxhj",
                    "slug": "ribirudo-waarudo",
                    "type_id": 1,
                    "created_at": "2019-08-18T06:04:38.000000Z",
                    "updated_at": "2023-12-23T18:15:17.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/ribirudo-waarudo/cover/eSqdpn5Gkxhj_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/ribirudo-waarudo/cover/eSqdpn5Gkxhj_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/ribirudo-waarudo/cover/eSqdpn5Gkxhj_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/ribirudo-waarudo/cover/eSqdpn5Gkxhj_thumb.jpg",
                    "href": "https://mangalib.me/ribirudo-waarudo",
                    "title_status_id": null
                },
                {
                    "id": 3640,
                    "name": "Tsuki ga Michibiku Isekai Douchuu",
                    "eng_name": "Moon-led Journey Across Another World",
                    "rus_name": "Лунный бог, приключение и другой мир",
                    "cover": "BwsIJ2LWpCk2",
                    "slug": "tsuki-ga-michibiku-isekai-douchuu",
                    "type_id": 1,
                    "created_at": "2017-12-19T22:11:46.000000Z",
                    "updated_at": "2023-12-23T18:14:31.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/tsuki-ga-michibiku-isekai-douchuu/cover/BwsIJ2LWpCk2_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/tsuki-ga-michibiku-isekai-douchuu/cover/BwsIJ2LWpCk2_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/tsuki-ga-michibiku-isekai-douchuu/cover/BwsIJ2LWpCk2_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/tsuki-ga-michibiku-isekai-douchuu/cover/BwsIJ2LWpCk2_thumb.jpg",
                    "href": "https://mangalib.me/tsuki-ga-michibiku-isekai-douchuu",
                    "title_status_id": null
                },
                {
                    "id": 9433,
                    "name": "Sensei wa Koi wo Oshierarenai",
                    "eng_name": "Sensei Can't Teach Me About Love",
                    "rus_name": "Сэнсэй не может научить меня любить",
                    "cover": "lAPkfl2OsORl",
                    "slug": "sensei-wa-koi-wo-oshierarenai",
                    "type_id": 1,
                    "created_at": "2019-02-07T09:55:28.000000Z",
                    "updated_at": "2023-12-23T18:13:15.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/sensei-wa-koi-wo-oshierarenai/cover/lAPkfl2OsORl_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/sensei-wa-koi-wo-oshierarenai/cover/lAPkfl2OsORl_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/sensei-wa-koi-wo-oshierarenai/cover/lAPkfl2OsORl_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/sensei-wa-koi-wo-oshierarenai/cover/lAPkfl2OsORl_thumb.jpg",
                    "href": "https://mangalib.me/sensei-wa-koi-wo-oshierarenai",
                    "title_status_id": null
                },
                {
                    "id": 13864,
                    "name": "Creepy Cat - Cat and my strange life",
                    "eng_name": "",
                    "rus_name": "Жуткий кот - Кот и моя странная жизнь",
                    "cover": "nDj9Q4NJbX8Q",
                    "slug": "creepy-cat-cat-and-my-strange-life",
                    "type_id": 1,
                    "created_at": "2019-07-07T05:53:34.000000Z",
                    "updated_at": "2023-12-23T18:11:25.000000Z",
                    "site": 1,
                    "type": "Манга",
                    "modelType": "manga",
                    "covers": {
                        "default": "https://cover.imglib.info/uploads/cover/creepy-cat-cat-and-my-strange-life/cover/nDj9Q4NJbX8Q_250x350.jpg",
                        "thumbnail": "https://cover.imglib.info/uploads/cover/creepy-cat-cat-and-my-strange-life/cover/nDj9Q4NJbX8Q_thumb.jpg"
                    },
                    "coverImage": "https://cover.imglib.info/uploads/cover/creepy-cat-cat-and-my-strange-life/cover/nDj9Q4NJbX8Q_250x350.jpg",
                    "coverImageThumbnail": "https://cover.imglib.info/uploads/cover/creepy-cat-cat-and-my-strange-life/cover/nDj9Q4NJbX8Q_thumb.jpg",
                    "href": "https://mangalib.me/creepy-cat-cat-and-my-strange-life",
                    "title_status_id": null
                }
            ],
    })
}